#!/usr/bin/env bash
# Ensure OPS_TEST_SECRET exists in .env for local Ops Eval Console (docs/29).
# - Key absent → generate once and append to .env
# - Key present with non-empty value → leave unchanged (URL stays stable)
# - Key present but empty (OPS_TEST_SECRET=) → intentional off; do not generate
# Prints the console URL when enabled. Optional: OPS_SECRET_STATUS_FILE → generated=0|1
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: ${ENV_FILE} missing; run: cp .env.example .env" >&2
  exit 1
fi

# True if an active (non-comment) KEY= line exists, even when value is empty.
env_has_key() {
  local key="$1"
  grep -Eq "^[[:space:]]*${key}=" "$ENV_FILE"
}

# Read KEY from .env: last active assignment; strip CR + inline # comments.
env_get() {
  local key="$1"
  local line val
  line="$(grep -E "^[[:space:]]*${key}=" "$ENV_FILE" | tail -n1 || true)"
  [[ -z "$line" ]] && return 0
  val="${line#*=}"
  val="${val%%$'\r'}"
  val="${val%%#*}"
  val="${val#"${val%%[![:space:]]*}"}"
  val="${val%"${val##*[![:space:]]}"}"
  if [[ "$val" == \"*\" ]]; then
    val="${val:1:${#val}-2}"
  elif [[ "$val" == \'*\' ]]; then
    val="${val:1:${#val}-2}"
  fi
  printf '%s' "$val"
}

secret="$(env_get OPS_TEST_SECRET)"
generated=0
ops_url=""

if ! env_has_key OPS_TEST_SECRET; then
  if command -v openssl >/dev/null 2>&1; then
    secret="$(openssl rand -hex 16)"
  else
    secret="$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
  fi
  {
    echo ""
    echo "# --- Ops Eval Console (auto-generated by make up / ensure_ops_test_secret; docs/29) ---"
    echo "OPS_TEST_SECRET=${secret}"
  } >>"$ENV_FILE"
  generated=1
  echo "==> OPS_TEST_SECRET generated and written to .env"
elif [[ -z "$secret" ]]; then
  echo "==> OPS_TEST_SECRET is empty (Ops Eval Console disabled; docs/29)"
else
  echo "==> OPS_TEST_SECRET already set (not overwritten)"
fi

if [[ -n "$secret" ]]; then
  domain="$(env_get PUBLIC_DOMAIN)"
  domain="${domain:-localhost}"
  http_port="$(env_get HTTP_PORT)"
  http_port="${http_port:-80}"
  host_port="$(env_get HOST_PORT)"
  host_port="${host_port:-443}"

  # Prefer plain HTTP on local stacks (HTTP_PORT=80 → no :port in URL).
  if [[ "$http_port" == "80" ]]; then
    ops_url="http://${domain}/ops/${secret}/test"
  elif [[ -n "$http_port" ]]; then
    ops_url="http://${domain}:${http_port}/ops/${secret}/test"
  else
    ops_url="https://${domain}:${host_port}/ops/${secret}/test"
  fi
  echo "==> Ops Eval Console: ${ops_url}"
fi

if [[ -n "${OPS_SECRET_STATUS_FILE:-}" ]]; then
  {
    echo "generated=${generated}"
    echo "ops_url=${ops_url}"
  } >"$OPS_SECRET_STATUS_FILE"
fi
