#!/usr/bin/env bash
# Resolve embed profile for make up / up-runtime / up-bench.
# Writes deploy/embedding.auto.env (gitignored). Compose loads it after .env.
#
# Policy (RET-4 / §14):
#   EMBEDDING_PROFILE=auto|small|large   (default auto)
#   suitable GPU (CUDA + VRAM ≥ EMBEDDING_GPU_MIN_MIB, default 8192)
#     → thenlper/gte-large @1024
#   otherwise → thenlper/gte-small @384
# MiniLM is no longer a production default.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${EMBEDDING_AUTO_ENV:-$ROOT/deploy/embedding.auto.env}"
MIN_MIB="${EMBEDDING_GPU_MIN_MIB:-8192}"

# Load .env keys we care about (do not export secrets broadly).
if [[ -f "$ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  set -a
  # Only pull profile / override knobs; ignore parse errors on odd lines.
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      EMBEDDING_PROFILE=*|EMBEDDING_MODEL=*|EMBEDDING_DIMENSIONS=*|EMBEDDING_BACKEND=*|EMBEDDING_GPU_MIN_MIB=*|EMBEDDING_FORCE_MODEL=*)
        eval "export $line" 2>/dev/null || true
        ;;
    esac
  done <"$ROOT/.env"
  set +a
fi

PROFILE="$(echo "${EMBEDDING_PROFILE:-auto}" | tr '[:upper:]' '[:lower:]')"
FORCE_MODEL="${EMBEDDING_FORCE_MODEL:-}"

gpu_vram_mib() {
  if ! command -v nvidia-smi >/dev/null 2>&1; then
    echo 0
    return
  fi
  local raw
  raw="$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 || true)"
  raw="$(echo "$raw" | tr -cd '0-9')"
  if [[ -z "$raw" ]]; then
    echo 0
  else
    echo "$raw"
  fi
}

pick_large=0
reason=""
case "$PROFILE" in
  large|gte-large|l)
    pick_large=1
    reason="EMBEDDING_PROFILE=$PROFILE"
    ;;
  small|gte-small|s)
    pick_large=0
    reason="EMBEDDING_PROFILE=$PROFILE"
    ;;
  auto|"")
    vram="$(gpu_vram_mib)"
    vram="${vram:-0}"
    if [[ "$vram" =~ ^[0-9]+$ ]] && (( vram >= MIN_MIB )); then
      pick_large=1
      reason="auto: nvidia VRAM ${vram}MiB ≥ ${MIN_MIB}MiB"
    else
      pick_large=0
      reason="auto: no suitable GPU (vram=${vram}MiB, need≥${MIN_MIB})"
    fi
    ;;
  *)
    echo "resolve_embedding_profile: unknown EMBEDDING_PROFILE=$PROFILE (use auto|small|large)" >&2
    exit 2
    ;;
esac

if [[ -n "$FORCE_MODEL" ]]; then
  MODEL="$FORCE_MODEL"
  if echo "$MODEL" | grep -qi 'gte-large'; then
    DIMS=1024
    INDEX_VER=10
    pick_large=1
  elif echo "$MODEL" | grep -qi 'gte-small'; then
    DIMS=384
    INDEX_VER=9
    pick_large=0
  else
    DIMS="${EMBEDDING_DIMENSIONS:-384}"
    INDEX_VER=9
  fi
  reason="EMBEDDING_FORCE_MODEL=$FORCE_MODEL ($reason)"
elif (( pick_large )); then
  MODEL="thenlper/gte-large"
  DIMS=1024
  INDEX_VER=10
else
  MODEL="thenlper/gte-small"
  DIMS=384
  INDEX_VER=9
fi

BACKEND="${EMBEDDING_BACKEND:-sentence_transformers}"
if (( pick_large )); then
  RESOLVED=large
else
  RESOLVED=small
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Generated by scripts/resolve_embedding_profile.sh — do not edit by hand.
# Regenerated on every make up / up-runtime / up-bench.
# Reason: ${reason}
EMBEDDING_BACKEND=${BACKEND}
EMBEDDING_MODEL=${MODEL}
EMBEDDING_DIMENSIONS=${DIMS}
EMBEDDING_INDEX_VERSION=${INDEX_VER}
EMBEDDING_PROFILE_RESOLVED=${RESOLVED}
EOF

echo "==> embedding profile: ${MODEL} @${DIMS}d (index≈${INDEX_VER}) — ${reason}"
echo "    wrote ${OUT}"
